# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils.ipynb.

# %% auto 0
__all__ = ['merge_dicts', 'binarize_age']

# %% ../nbs/utils.ipynb 1
import pandas as pd

# %% ../nbs/utils.ipynb 2
def merge_dicts(x):
    return {k: v for d in x.dropna() for k, v in d.items()}

# %% ../nbs/utils.ipynb 3
def binarize_age(age_col):
    age_col = age_col.fillna(150)
    
    bins = [0,30,40,50,60,70,80,100,150]
    labels= list(range(len(bins) - 1))
    
    return pd.cut(age_col, bins=bins, labels=labels, include_lowest=True).astype(int)
